swagger: "2.0"
basePath: /api/v1
info:
  version: 1.0.0
  title: PCO Contentful service api
  description: API to serve content from contentful and handle cache for pco applications
consumes:
  - application/json
produces:
  - application/json
definitions:
  health:
    required:
      - status
    properties:
      status:
        type: string
  path_example:
    required:
      - val
    properties:
      val:
        type: string

paths:
  /health:
    get:
      description: HealthCheck to test communication
      operationId: Ping
      responses:
        200:
          description: Returns the matching applications
          schema:
            $ref: "#/definitions/health"
  /example/{value}:
    post:
      description: post an example and get same example description
      parameters:
        - value:
          in: path
          required: true
          description: Value from path
          schema:
            type: string
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/path_example"
        400:
          description: Bad Request, value cannot be parsed
